dist: xenial # needed to use python 3.7
language: python
branches:
  only:
    - master
python:
  - 3.7
install:
  - pip install -U pip
  - pip install pipenv
  - pipenv install # set up the environment
  - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.1.0 # install vale
  - export PATH="./bin:$PATH"
script:
  - skip # Travis requires a `script` property, but we do not need it
stages:
  - build and test
  - deploy
jobs:
  include:
    - stage: build and test # This stage builds and lints in parallel
      name: Build
      script: pipenv run make html # build the docs
    - script: vale --minAlertLevel error source # run vale
      name: Test
    - stage: deploy
      name: Deploy to GitHub Pages
      if: (NOT type IN (pull_request)) AND (branch = master) # only deploy if merging on master
      script: pipenv run make html
      deploy:
        provider: pages # deploy on github pages
        skip_cleanup: true
        github_token: "$token" # defined via the Travis interface
        local_dir: build/html
git:
  depth: false # fetch all branches
language: ruby
rvm:
  - 2.6
services: [docker]
matrix:
  include:
    - env: RESTYLER=astyle
    - env: RESTYLER=autopep8
    - env: RESTYLER=black
    - env: RESTYLER=google-java-format
    - env: RESTYLER=prettier
    - env: RESTYLER=prettier-json
    - env: RESTYLER=prettier-markdown
    - env: RESTYLER=prettier-ruby
    - env: RESTYLER=prettier-yaml
    - env: RESTYLER=reorder-python-imports
    - env: RESTYLER=rubocop
    - env: RESTYLER=shellharden
    - env: RESTYLER=whitespace
install: gem install rspec
script: |
  # failure means we're on the "push" job. we'll just diff against parent
  mb=$(git merge-base master HEAD 2>/dev/null || echo "HEAD^")

  if ! git diff --name-only "$mb" | grep -q "^${RESTYLER}/"; then
    echo "$RESTYLER unchanged, skipping."
    exit 0
  fi

  parent=$(./build/restyler-meta overrides "$RESTYLER")

  if [ -n "$parent" ]; then
    make "$parent"/Dockerfile.built "$RESTYLER".tested
  else
    make "$RESTYLER"/Dockerfile.tested
  fi
