language: node_js

node_js:
  - "5.6"
  - "4.3"
  - "0.12"
  - "0.10"

env:
  - CC=gcc-4.8 CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
